### ISSUE TITLE
April 2017 Meeting

### ISSUE THREAD

**Issue by mattjmorrison** [pyowa/pyowa.github.io#15]
For new meetings collect the following information

* Speaker
  - [ ] Speaker Name & brief bio
  - [ ] Topic & brief description
* Food/Drink Sponsor
  - [ ] Website
  - [ ] Any info they would like included
* Location Sponsor
  - [ ] Website
  - [ ] Any info they would like included
  - [ ] URL to map
  - [ ] Parking instructions
  - [ ] Building entering instructions
  - [ ] How to get the the room

**Comment by jessehorne** [comment]
Here's the information provided to me in an email by Megan Modlin, at Source Allies. They have agreed with be the venue for Aprils meeting, and their location is just what we need.
```
    Seating for 80+  
    Large projector screen (180")
    Connect via HDMI, AirPlay, Chromecast or Miracast
    A/V setup with two wireless microphones
    Also equipped with a Chromebox for meetings setup


Address

4501 NW Urbandale Dr, Urbandale, IA 50322
Entrance is on the South side of the building



Blurb about Source Allies

Source Allies is a local technical consultancy who values collaboration, craftsmanship, and an ownership mentality. We provide a home to our teammates where we encourage each other to grow not only technically, but as peers & consultants. This is evident in the quality software we deliver to clients.

    Learn about our “ownership mentality” at: www.sourceallies.com
```

**Comment by michaelwclark** [comment]
Gravitate DSM Info:

Seating for 30+ (over 30 will need to bring chairs)
Large Mobile TV
Apple Connect/HDMI

Address:
206 6TH AVE, THIRD FLOOR, DES MOINES, IA, 50309

$20/meeting w/ Membership (I have one)
A few days notice is recomended

http://www.gravitatedsm.com/

**Comment by driscollis** [comment]
**About Mike Driscoll**

Mike has been programming with Python for over a decade. He is the creative mind behind the popular Python blog, [Mouse Vs. the Python](http://www.blog.pythonlibrary.org/) and the author of several books on the Python programming language. Mike is a member of the Python Software Foundation and has worked as a technical reviewer of Python books for Packt Publishing.

**The Topic**

Intro to Creating PDFs with Reportlab

Many jobs require you to produce documents programmatically. One of the most popular document formats is Adobe's Portable Document Format (PDF). The Reportlab package allows Python developers to generate PDFs in a very straight-forward manner. In this talk, Mike will help you learn how to do the following:

- Create a simple PDF
- Draw text, lines, circles, rectangles
- Insert graphics
- Learn about formatting your text
- Add tables
- Create a multi-page document

There might be more depending on how quickly we get through all that. I'm going to write up a simple data generator and parser too so we can play around with document processing.

**Comment by mattjmorrison** [comment]
thanks @driscollis I'll get the website updated this evening and update the mailing list and twitter.
