### ISSUE TITLE
Interning

### ISSUE THREAD

**Issue by jakobpederson** [pyowa/pyowa.github.io#18]
For new meetings provide the following information

* Speaker
  - [x] Name & brief bio
Jakob Pederson
I'm a recent transplant from Seattle looking to become a dev here in Des Moines.
  - [x] Topic & brief description
I was volunteered to speak about my experience as an intern at IMT Apps. I'll try and cover what the experience was like and what I learned from it.
* Food/Drink Sponsor
  - [ ] Link to website
  - [ ] Any info they would like included
* Location Sponsor
  - [ ] Link to website
  - [ ] Any info they would like included
  - [ ] URL to a map
  - [ ] Parking instructions
  - [ ] Building entering instructions
  - [ ] How to get the the room

**Comment by mattjmorrison** [comment]
thanks @jakobpederson
