### ISSUE TITLE
August 2017 Meeting

### ISSUE THREAD

**Issue by TomAugspurger** [pyowa/pyowa.github.io#23]
There was some talk about me presenting my experience at SciPy 2017. Personally I think that'd be a bit dry (for me anyway; I already lived it 😄 ), so I'm proposing the alternative topic of parallel programming in Python. We'd do a bit of background on threading vs. processes (the GIL mostly) and then look a [dask](https://dask.pydata.org) and [distributed](https://distributed.readthedocs.org) in more detail (these were born in the scientific computing space, but they can be more broadly useful I think; I'll try to emphasize that).

What date would the meeting be on? I can't remember if it's the first or second Tuesday of the month.

* Speaker
  - [ ] Name & brief bio
  - [ ] Topic & brief description
* Food/Drink Sponsor
  - [ ] Link to website
  - [ ] Any info they would like included
* Location Sponsor
  - [ ] Link to website
  - [ ] Any info they would like included
  - [ ] URL to a map
  - [ ] Parking instructions
  - [ ] Building entering instructions
  - [ ] How to get the the room

**Comment by mattjmorrison** [comment]
@TomAugspurger Sounds good, thanks! Can you add (as a comment) a brief bio and summary of the topic that I can use to update the website and mailing list?

**Comment by TomAugspurger** [comment]
Bio: I'm a data scientist at Continuum Analytics, and a maintainer of pandas and dask.

Topic: We'll cover parallel programming in Python at a high level. We'll discuss the GIL and how it affects the choice between Multiprocessing and threaded parallelism. We'll briefly see the concurrent.futures interface, before going into more detail on dask and distributed.

**Comment by mattjmorrison** [comment]
thanks @TomAugspurger
