### ISSUE TITLE
September 2017

### ISSUE THREAD

**Issue by mattjmorrison** [pyowa/pyowa.github.io#25]
For new meetings provide the following information

* Speaker
  - [ ] Name & brief bio
  - [ ] Topic & brief description
* Food/Drink Sponsor
  - [ ] Link to website
  - [ ] Any info they would like included
* Location Sponsor
  - [ ] Link to website
  - [ ] Any info they would like included
  - [ ] URL to a map
  - [ ] Parking instructions
  - [ ] Building entering instructions
  - [ ] How to get the the room

**Comment by davidbody** [comment]
# What is Machine Learning?

Our lives are influenced by data and algorithms more than most of us realize. Movie and product recommendations, speech recognition, spam filtering, fraud detection, medical diagnoses, and even autonomous vehicles are all powered by machine learning, a subfield of computer science dealing with statistical pattern recognition and artificial intelligence.

This session will introduce you to the field of machine learning and explain basic concepts such as supervised and unsupervised learning. It will also provide an overview of basic types of machine learning problems such as regression, classification, and clustering.

We'll cover one concrete example, which has become the "hello world" problem of machine learning: We'll train a neural network to recognize handwriting using the MNIST handwritten digit database. (This example will be in Python using [TensorFlow](https://www.tensorflow.org/) and [Keras](https://keras.io/).)

This is a very mathematical subject, but we'll focus on developing intuition about how machine learning works conceptually.

You'll come away with a basic understanding of what machine learning is and enough of an idea of how it works to decide if you want to learn more.

Versions of this talk were or will be presented at [Iowa Code Camp](http://www.iowacodecamp.com/), [Kansas City Developer Conference](http://www.kcdc.info/), and [Prairie.Code()](https://prairiecode.amegala.com/).

# Speaker

David W. Body is an experienced software developer who is interested in data science, machine learning, and related areas. His company is [Big Creek Software, LLC](https://www.bigcreek.com) and he is on Twitter as [@david_body](https://twitter.com/david_body). David is available for freelance consulting and contract work.
