### ISSUE TITLE
September 4th

### ISSUE THREAD

**Issue by jessehorne** [pyowa/pyowa.github.io#48]
* Speaker
  - Jesse Horne | Web Developer with two years of experience. Worked as PHP Developer in Wyoming before moving to Iowa to work for TEKsystems at Pioneer. Started writing code at a young age. Fairly interesting involvement in anti-war, anti-pipeline, and anti-prison activism.
  - HiringDSM: The Open Source Job Board Project for Des Moines
  - https://hiringdsm.com
  - https://github.com/hiringdsm

HiringDSM is an open source job board. The frontend is written using Laravel which consumes a RESTful JSON API written in Python using tools such as Flask, Flask-JWT, Flask-Restless, Flask-Admin, etc.. I will be talking about the API primarily, why I picked the tools I did, how I setup the project and how the tools used have helped rapidly produce this project. I hope that this presentation will serve as a decent introduction to using Flask for API's and address concerns/questions with RESTful API development in general. I also hope to build up community support for the project and will discuss the contributing process which will let members of the community see how open source projects can be managed using GitHub and widely accepted/adopted strategies for organization of those projects.

* Food/Drink Sponsor
  - [ ] Link to website
  - [ ] Any info they would like included
* Location Sponsor
  - [ ] Link to website
  - [ ] Any info they would like included
  - [ ] URL to a map
  - [ ] Parking instructions
  - [ ] Building entering instructions
  - [ ] How to get the the room

**Comment by mattjmorrison** [comment]
@jessehorne Are you still good for this to go public for next week's meeting?

**Comment by mattjmorrison** [comment]
closed by #50
