### ISSUE TITLE
A Pythonic Introduction to  SMT

### ISSUE THREAD

**Issue by chadbrewbaker** [pyowa/pyowa.github.io#49]
Any slot will work as long as I have at least two weeks notice.

* Speaker
  - [ ] Name & brief bio: Chad Brewbaker consults through Flying Dog Solutions LLC with a focus full stack AWS development, build engineering including static analysis, mathematical modeling, and mobile phone forensics.
  - [ ] Topic & brief description :  "A Pythonic Introduction to  SMT"  SMT or SAT Modulo Theories is a powerful technology built upon the efficient SAT (boolean logic) solvers developed in the 2000s.  It is serious AI with serious applications. We will go over the Python API for the Microsoft Z3 SMT solver and show you can use it leverage it for superhuman calculations to amaze your coworkers and crush the competition with optimal solutions for seemingly intractable problems.

**Comment by mattjmorrison** [comment]
@chadbrewbaker it looks like @jessehorne is going to present #48 on Sept 4th, October 2nd would be the next meeting - we can tentatively plan on that if that works for you. Thanks for volunteering to talk!

**Comment by mattjmorrison** [comment]
Hi @chadbrewbaker, will October 2nd work out for you to present this topic? If so, I'll go ahead and get the website updated.

**Comment by chadbrewbaker** [comment]
October 2nd is great. Put me down.

**Comment by mattjmorrison** [comment]
@chadbrewbaker thanks!
