### ISSUE TITLE
Easy software deployment with Pex

### ISSUE THREAD

**Issue by sherzberg** [pyowa/pyowa.github.io#53]
For new meetings provide the following information

* Speaker
  - [ ] Name & brief bio: Spencer Herzberg is contractor working currently in the cloud devops space. His background is software development but slowly moved into ops automation. He loves reducing complexity and loves automation. Outside of work, he spends most of his time with his two little girls and lovely wife and when possible, he works on being a hobbyist woodworker.
  - [ ] Topic & brief description: Do you struggle to setup and maintain python tool installation across developers machines and servers? Do you wish tool updates were as smooth as a single file replacement? Pex may be the answer you have looking for. Pex is a tool that will generate a single file that contains your python based tools as well as all of its dependencies. Installation becomes as easy as a file copy. This talk will cover how the tool works, how to use it, and some real world examples.

**Comment by mattjmorrison** [comment]
@sherzberg thanks!
