### ISSUE TITLE
Juypter Notebooks

### ISSUE THREAD

**Issue by ehennis** [pyowa/pyowa.github.io#56]
For new meetings provide the following information

* Speaker
  - [ ] Evan Hennis. Senior .NET developer trying to break into data science
  - [ ] Jupyter Notebooks: A great way to teach using problem-based learning.
* Food/Drink Sponsor
  - [ ] Link to website
  - [ ] Any info they would like included
* Location Sponsor
  - [ ] Link to website
  - [ ] Any info they would like included
  - [ ] URL to a map
  - [ ] Parking instructions
  - [ ] Building entering instructions
  - [ ] How to get the the room

**Comment by mattjmorrison** [comment]
@ehennis would you want to discuss this next month? @driscollis also volunteered to discuss this topic also...

**Comment by ehennis** [comment]
The other person can do it since I talked last week.

**Comment by mattjmorrison** [comment]
@driscollis Would you be available to talk about Jupyter notebooks on April 2nd?

**Comment by driscollis** [comment]
Yeah, I can probably throw something together

**Comment by driscollis** [comment]
For new meetings provide the following information

* Speaker
  - [ ] Mike Driscoll. Python Subject Matter Expert, author, blogger
  - [ ] An intro to Jupyter Notebooks - Learn how to use Notebooks for learning and presenting data with Python in a browser

**Comment by mattjmorrison** [comment]
Thanks @driscollis!
