### ISSUE TITLE
Reinforcement Learning

### ISSUE THREAD

**Issue by ehennis** [pyowa/pyowa.github.io#57]
For new meetings provide the following information

* Speaker
  - [ ] Evan Hennis. Senior .NET developer trying to break into data science
  - [ ] Reinforcement Learning: Showing the evolution of the Q learning algorithm from 4x4 grid exploration to defeating Atari games. (I gave a similar talk at the Iowa Code camp so skip if you have heard it!)
* Food/Drink Sponsor
  - [ ] Link to website
  - [ ] Any info they would like included
* Location Sponsor
  - [ ] Link to website
  - [ ] Any info they would like included
  - [ ] URL to a map
  - [ ] Parking instructions
  - [ ] Building entering instructions
  - [ ] How to get the the room

**Comment by mattjmorrison** [comment]
@ehennis would you be willing to give this talk at our March 5th meeting?

**Comment by ehennis** [comment]
Yeah, I should be able to pull everything together by March 5th.

**Comment by mattjmorrison** [comment]
@ehennis great, thanks! I will get the website updated and send out the announcement. Thanks again!

**Comment by ehennis** [comment]
Is there a mailing list or do you just post it on Twitter?

**Comment by TomAugspurger** [comment]
There's a mailing list at https://groups.google.com/forum/#!forum/pyowa

**Comment by mattjmorrison** [comment]
Thanks @ehennis
