### ISSUE TITLE
Lenderclose location issue.

### ISSUE THREAD

**Issue by chadbrewbaker** [pyowa/pyowa.github.io#58]
A tenant in the building has raised unsubstantiated concerns with West Des Moines Police over further Pyowa meetings at the LenderClose office or Iowa Ruby Brigade meetings at Shift. This is no reflection on Lenderclose or Shift, they have been  great host.

I'm of the opinion to avoid conflict  we should meet next month at Gravitate WDM or see if we can get the back room of the Panera on Westown where the Python/R coffee groups on Saturdays.

**Comment by ehennis** [comment]
This is only my first week in this group so forgive me if this has already been discussed but the .NET user group would sometimes meet in the basement of the Source Allies building on 104th and Meredith in Urbandale. It is a pretty big space and SA seems pretty welcoming.

**Comment by mattjmorrison** [comment]
@ehennis thanks - we're always looking for ways to reach more people who may be interested in checking out our group.

@chadbrewbaker while I absolutely want to respect the wishes of the building tenants and obviously cooperate with law enforcement my understanding of the facts are a bit different than the way that you have presented them. It is my understanding that no tenants (or law enforcement) have any concerns with having any user groups host meetings in their building, as far as I am aware all user groups who have been hosted are perfectly well behaved guests that follow any and all required guidelines necessary to meet in that location. I do not have all of the facts, but based on what I know it sounds like there was a single individual who may have been in violation of a restraining order (or something along those lines) given the group's proximity to an employee of another building tenant.

LenderClose is a great sponsor and host and as long as they are interested, willing, and able to be a part of our community I want to support that. I also want anyone to be able to attend our meetings. I would, however, put the onus on the individual attendee to ensure that by attending one of our meetings they are not in any way violating any legal constraints that they may have.

If there are additional sponsors and/or hosts that we should be working with I am more than happy to meet in different places, dates, times, etc... so if you have some contacts that you would like to put me in touch with please do.

**Comment by chadbrewbaker** [comment]
Pyowa moved to that building against the wishes of the tenant. That wasn't a decision I had any input on.  My only interest is in avoiding conflict. I don't blame Pyowa leadership for being defiant, but they will have to live with the conflict of going against the tenant's wishes. The conflict I can't get on board with is putting the host into further conflict with the other tenant. I think that is rude.

**Comment by chadbrewbaker** [comment]
Pyowa moved to that building against the wishes of the tenant. That wasn't a decision I had any input on.  My only interest is in avoiding conflict. I don't blame Pyowa leadership for being defiant, but they will have to live with the conflict of going against the tenant's wishes. The conflict I can't get on board with is putting the host into further conflict with the other tenant. I think that is rude.
